version: '2'
services:
  zookeeper:
    image: zookeeper:3.4
    container_name: zookeeper
    restart: always
    ports:
    - 2181
  nimbus:
    image: storm:1.1.0
    container_name: nimbus
    hostname: nimbus
    restart: always
    command: storm --config /conf/storm.yaml nimbus
    ports:
    - 6627
    depends_on:
    - zookeeper
    - pacemaker
    links:
    - zookeeper:zk
    - pacemaker:pacemaker
    volumes:
    - ./storm.yaml:/conf/storm.yaml
  worker:
    image: storm:1.1
    container_name: worker
    command: storm --config /conf/storm.yaml supervisor
    depends_on:
    - nimbus
    - zookeeper
    links:
    - nimbus:nimbus
    - zookeeper:zk
    restart: always
    volumes:
    - ./storm.yaml:/conf/storm.yaml
  ui:
    image: storm:1.1
    container_name: ui
    command: storm --config /conf/storm.yaml ui
    ports:
    - 8080:8080
    depends_on:
    - nimbus
    - zookeeper
    links:
    - nimbus:nimbus
    - zookeeper:zk
    restart: always
    volumes:
    - ./storm.yaml:/conf/storm.yaml
  pacemaker:
    image: storm:1.1
    container_name: pacemaker
    hostname: pacemaker
    command: storm --config /conf/storm.yaml pacemaker
    ports:
    - 6699:6699
    restart: always
    volumes:
    - ./storm.yaml:/conf/storm.yaml